import { index, layout, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  route('login', 'routes/login.tsx'),
  layout('routes/shell.tsx', [
    index('routes/dashboard.tsx'),
    route('chat/:conversationId?', 'routes/chat.tsx'),
    route('journal', 'routes/journal.tsx'),
    route('managers', 'routes/managers.tsx', [route(':id', 'routes/manager-detail.tsx')]),
    route('memory', 'routes/memory.tsx', [route(':slug', 'routes/memory-detail.tsx')]),
    route('practices', 'routes/practices.tsx', [route(':slug', 'routes/practice-detail.tsx')]),
    route('approvals', 'routes/approvals.tsx'),
    route('approvals/answered/:date?/:approvalId?', 'routes/approvals-answered.tsx'),
    route('approvals/item/:approvalId', 'routes/approvals-item.tsx'),
    route('commitments', 'routes/commitments.tsx'),
    route('reports/:date?/:reportId?', 'routes/reports.tsx'),
    route('usage', 'routes/usage.tsx'),
    route('tokens', 'routes/tokens.tsx'),
    route('access', 'routes/access.tsx'),
    route('permissions', 'routes/permissions.tsx'),
    route('env-vars', 'routes/env-vars.tsx'),
    route('codex', 'routes/codex.tsx'),
    route('profile', 'routes/profile.tsx'),
    route('mcp-servers', 'routes/mcp-servers.tsx'),
    route('plugins', 'routes/plugins.tsx'),
    route('integrations', 'routes/integrations.tsx'),
    route('files', 'routes/files.tsx'),
    route('dropped', 'routes/dropped.tsx'),
    route('archive', 'routes/archive.tsx'),
    route('archive/:id', 'routes/archive-detail.tsx'),
    route('inbox', 'routes/inbox.tsx'),
    route('schedule', 'routes/schedule.tsx'),
    route('settings', 'routes/settings.tsx'),
    route('progress', 'routes/progress.tsx'),
    route('*', 'routes/not-found.tsx'),
  ]),
] satisfies RouteConfig;
